version: '3.8'

services:
  client:
    build:
      target: builder
    environment:
      - VITE_MODE=dev
      - VITE_API_HOST=http://localhost:5000
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
